// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA213aNrRznw3bUxu2G_M8VgyBnyXnxyPw',
    appId: '1:307336454737:web:8a3ac23b274043fcffce70',
    messagingSenderId: '307336454737',
    projectId: 'home-pharmacy-5b573',
    authDomain: 'home-pharmacy-5b573.firebaseapp.com',
    storageBucket: 'home-pharmacy-5b573.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6jHy1UHRjegqVsfUkqE5LsPlWlfKvQIg',
    appId: '1:307336454737:android:539d2091489f7506ffce70',
    messagingSenderId: '307336454737',
    projectId: 'home-pharmacy-5b573',
    storageBucket: 'home-pharmacy-5b573.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9VW_PGusAz5pvh8YYCPYDUn_tzz3Ot-I',
    appId: '1:307336454737:ios:c1b1adf543c66b87ffce70',
    messagingSenderId: '307336454737',
    projectId: 'home-pharmacy-5b573',
    storageBucket: 'home-pharmacy-5b573.appspot.com',
    iosClientId: '307336454737-r4dk75d9s7cmfhpunansnqoagsgfje1f.apps.googleusercontent.com',
    iosBundleId: 'com.example.homePharmacy',
  );
}
